#
# This values file is used for local development and testing.
# It disables some features and reduces the resource requirements to run the Camunda Platform locally.
#
global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

#
# Management Cluster.
#

identity:
  enabled: false

identityKeycloak:
  enabled: false

#
# Orchestration Cluster.
#

connectors:
  inbound:
    mode: disabled

orchestration:
  replicas: 1
  clusterSize: "1"
  partitionCount: "1"
  replicationFactor: "1"
  pvcSize: 10Gi
  env:
  - name: SPRING_PROFILES_INCLUDE
    value: "backup"
  extraConfiguration:
    application-backup.yaml: |
      camunda:
        data:
          backup:
            repository-name: "camunda-backup"

      zeebe:
        broker:
          data:
            backup:
              enabled: true
              store: S3
              s3:
                bucketName: camunda
                forcePathStyleAccess: true
                endpoint: http://minio:9000
                accessKey: minioadmin
                secretKey: minioadmin
                region: us-east-1
                basePath: zeebe

optimize:
  env:
  - name: CAMUNDA_OPTIMIZE_BACKUP_REPOSITORY_NAME
    value: "optimize-backup"

elasticsearch:
  master:
    masterOnly: false
    replicaCount: 1
    persistence:
      size: 10Gi
  data:
    replicaCount: 0
  coordinating:
    replicaCount: 0
  ingest:
    replicaCount: 0
  image:
    repository: bitnamilegacy/elasticsearch
    tag: 8.18.0
  global:
   kibanaEnabled: true
  kibana:
    image:
      repository: bitnamilegacy/kibana
      tag: 8.18.0 
    readinessProbe:
      enabled: false
  initScripts:
    init-keystore.sh: |
      #!/bin/bash
      set -e

      echo "Adding S3 access keys to Elasticsearch keystore..."

      # Add S3 client default keys to the keystore
      echo "$S3_SECRET_KEY" | elasticsearch-keystore add -f -x s3.client.default.secret_key
      echo "$S3_ACCESS_KEY" | elasticsearch-keystore add -f -x s3.client.default.access_key

  extraEnvVars:
  - name: S3_SECRET_KEY
    value: minioadmin
  - name: S3_ACCESS_KEY
    value: minioadmin